[project]
name = "pedal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "mpmath>=1.3.0",
    "numpy>=2.4.2",
    "plotly>=6.5.2",
    "scipy>=1.17.0",
]
